### ISSUE TITLE
[Errno 21] Is a directory 

### ISSUE THREAD

**Issue by jimpriest** [chfoo/wpull#320]
I'm trying to pull down a static copy of a Drupal site.  It's multilingual so we have directories for each language - ie: /en, /fr, /ja

I'm trying to just pull down the English directory - /en

If I do  wpull mydomain.com/en  it will run for awhile and then randomly stop with:

```
2016-03-31 19:56:03,646 - wpull.processor.web - INFO - Fetching ‘http://mydomain.com/en/services/consulting’.
2016-03-31 19:56:03,846 - wpull.app - ERROR - [Errno 21] Is a directory: 'mydomain.com/en.d/services/consulting'
2016-03-31 19:56:03,846 - wpull.app - INFO - FINISHED.
```
Each time I run wpull it will stop at a different directory or I get:

`ERROR [Errno 20] Not a directory: 'mydomain.com/en.d/success-stories/sprint'`

Not sure where/what the en.d is from.

If I instead try to filter with --include-directories it doesn't do anything:

```
wpull  mydomain.com --include-directories en
INFO FINISHED.
INFO Duration: 0:00:00. Speed: -- B/s.
INFO Downloaded: 0 files, 0.0 B.
INFO Exiting with status 0.
```

- Fedora 23
- Python 3.4.3
- wpull 1.2.3

Am I doing something wrong? Or missing an option?  If I do something similar with wget I get a /en directory. 

I'm testing wpull as a wget replacement. I'm mainly curious if wpull mimics the wget behaviour when using the --reject option...  wget will still pull that content down, then if rejected, it will delete it. 

Ideally I'd like to reject something and have it NOT downloaded.

Thanks,
Jim

**Comment by chfoo** [comment]
I am assuming that it's getting `mydomain.com/en` which gets saved to `en`. Then it tries to fetch `mydomain.com/en/services/` but since `en` is a file, it creates `en.d` as a directory which is what is seen here. If I recall correctly, Wget will just delete the `en` file. 

I think the bug is due to confusion in the URL file/directory handling. It looks like `mydomain.com/en.d/services/consulting/` was fetched so the directory `en.d/services/consulting/` was created with the file `en.d/services/consulting/index.html` . Now when it fetches `mydomain.com/en.d/services/consulting`, it can't create the file `en.d/services/consulting`.

As a workaround, you can try `mydomain.com/en/` and `--reject-regex` or some other option to filter out index URLs that don't end a slash.

The `--include-directories` option follows the same syntax described in Wget's documentation, so you need the leading slash so like `/en`. Also, because it tries to follow Wget's convoluted semantics, specifying `mydomain.com --include-directories /en` won't grab anything because the `mydomain.com` is outside the `/en` directory.

I also got your email about the `--reject` option. Wpull's URL exclusion matching rules work before the downloads so it should never download and then delete files.

**Comment by jimpriest** [comment]
Thank you for the very detailed reply!

I used the --adjust-extension option to force en to en.html and now don't get an error!
